### ISSUE TITLE
Set a bad themes qt applications + setting keyboard layout

### ISSUE THREAD

**Issue by Manazius** [evolve-os/budgie-desktop#111]
Hi! Why are installed incorrectly topic qt-applications? Where and how to configure it? Although Gnome Shell is displayed normally. 
Where and how to customize the keyboard layout? I need Russian and English (Similarly, in the Gnome Shell keyboard layout switches normally.)
PS. I liked your desktop environment, maybe I can help you with translation into Russian.
I use Arch Linux

**Comment by ikeydoherty** [comment]
I'm sorry I'm not sure what the bug is here. Please clarify.

**Comment by ikeydoherty** [comment]
Qt applications are fixed! :) e6d9939658c919f71cc2366a6ec1440b752edc5f
