### ISSUE TITLE
Middle and right click on maximize behave unexpected

### ISSUE THREAD

**Issue by lightonflux** [evolve-os/budgie-desktop#112]
On most linux DE's the behaviour is as the following:

 * Middle click on maximize expands window vertically
 * Right click on maximize expands window horizontally

When you try that in budgie the click behaves as if you clicked on the window bar not the maximize button.

**Comment by ikeydoherty** [comment]
Don't think we can alter something that deeply, and tbh its not something I really want to support in Budgie, we already have a tiling behaviour by dragging to a screen edge
