### ISSUE TITLE
[Feature Request] global menus

### ISSUE THREAD

**Issue by Thomas-O** [evolve-os/budgie-desktop#115]
Please will you add a global menus option? 

The space saving global menus are the only reason I have yet to fully abandon Unity for Budgie or Pantheon.

Thanks for your time.

Thomas

**Comment by rilian-la-te** [comment]
For GTK3 - no, AFAIK, it can done even without indicators. For GTK2 - yes, if it is done via DbusMenu. But if you will use old GlobalMenu or new TopMenu implementation - it will work without patch.

But I think that simple GTK3-only Global Menu is enough.

**Comment by kallisti5** [comment]
eew.  No global menus, they are the worst design feature known to man.

**Comment by ikeydoherty** [comment]
Closing as I personally have no interest in implementing this. However I'm happy to accept patches to add an optional global menubar applet.

**Comment by JoshStrobl** [comment]
No. I'm not re-opening this, I have no plans on supporting it. I'm leaving it to Budgie applet developers to implement it outside of core.
