### ISSUE TITLE
Super key not doing anything

### ISSUE THREAD

**Issue by PureTryOut** [evolve-os/budgie-desktop#118]
Whenever someone presses the super key (Windows key) they expect the start menu to come up, sadly this is not the case with Budgie. Is it possible to add this behaviour?

**Comment by ikeydoherty** [comment]
@juhp its not hardcoded.

```
gsettings get org.gnome.desktop.wm.keybindings panel-main-menu
['Super_L']
```

This is the default on Evolve OS

By default Mutter binds the same key to the overlay key, which is no use to us, so we set it to F12:

```
↠ gsettings get org.gnome.mutter overlay-key
'F12'
```

As this is a distribution and local configuration issue, I'm going to close this.
