### ISSUE TITLE
Cannot logout when gnome-control-center is open

### ISSUE THREAD

**Issue by LeoIannacone** [evolve-os/budgie-desktop#119]
This is odd .. I can't logout (I did not try the other options) while gcc is open ...

Someone else can confirm this ?

Ubuntu 14.10
gtk+_3.14.4-0ubuntu1~utopic3 
gnome-control-center_3.14.0-1ubuntu1~utopic1

**Comment by ikeydoherty** [comment]
Lack of response will lead to autoclose in a few days...

**Comment by ikeydoherty** [comment]
That certainly qualifies as a few days.
