### ISSUE TITLE
notification area icons are invisible

### ISSUE THREAD

**Issue by juhp** [evolve-os/budgie-desktop#120]
I am testing on Fedora 20 and for both v7 and v8 (and v6 too iirc)
the notification icons are not visible: so I can't see the network status
(NetworkManager icon) or the ibus input method icon, which is annoying.

The icons are actually running and working, but just showing black on black,
ie clicking on where the invisible icons are brings up there menus.
So I think it just a question of fixing the panel to show the icons correctly.
Presumably they show okay on EvolveOS?

Any more information I can provide?

**Comment by kallisti5** [comment]
Just saw this issue on ArchLinux (git head).  Seems to happen when reordering the panel applets and clicking on "place in status area" for random applets. All that shows up is the first icon (here it's the network icon)

**Comment by ikeydoherty** [comment]
Detailed explanation of the issue https://plus.google.com/+EvolveosOfficial/posts/FX3XG2ZxV3r

**Comment by ikeydoherty** [comment]
Gonna have to close as a no-fix I'm afraid. The original condition on including the tray was it gets minimal support, an interim measure. I'm happy to accept patches, ofc, but given the explanation its not a trivial fix and would require a huge overhaul of budgie for the sake of a legacy system.

Sorry dudes.
