### ISSUE TITLE
transparent panel menus

### ISSUE THREAD

**Issue by juhp** [evolve-os/budgie-desktop#121]
After updating to v8 the popup menus for the panel are now transparent
which can make them very hard to read.

I am testing on Fedora 20.

![screenshot from 2014-11-28 15 50 31](https://cloud.githubusercontent.com/assets/82731/5224378/5fd5c564-7716-11e4-9adf-240356cd39b6.png)

**Comment by Justinzobel** [comment]
What GTK theme are you using? If it's Adwaita it is not supported. Try Vertex theme.

**Comment by ikeydoherty** [comment]
Sadly this is the 3.10 Adwaita issues, as @Justinzobel has indicated. Given our recent drop of 3.10 support, I must close this report as unresolved (Though @Justinzobel's solution is correct!)
