### ISSUE TITLE
cannot pin some apps

### ISSUE THREAD

**Issue by lucazade** [evolve-os/budgie-desktop#131]
I'm not able to pin some apps to the panel for example nautilus or gedit.

In the dconf the entries for these apps are wrong:
it stores 'nautilus.desktop' but it should be 'org.gnome.Nautilus.desktop'
the same for gedit.. 'gedit.desktop' but the correct is 'org.gnome.gedit.desktop'

**Comment by nlaplante** [comment]
Gnome Terminal cannot be pinned too.

**Comment by ikeydoherty** [comment]
I have gnome-terminal pinned on my budgie setup ... please be more specific and state which version of gnome-terminal you have

**Comment by nlaplante** [comment]
It's 3.18.3 on Fedora 23.

[xprop patebin](http://pastebin.com/9rGaA9up)

**Comment by ikeydoherty** [comment]
Fixed in git - I was only able to fix this because I imported the patches from Fedora which use some patches from GNOME Terminal `3.20.x` :)
