### ISSUE TITLE
[Enhancement] Meta key menu launch

### ISSUE THREAD

**Issue by kallisti5** [evolve-os/budgie-desktop#149]
budgie would see a huge usability improvement from having the meta key (windows key) open the budgie menu.  This would enable the type and run everyone loves so much :-)  (meta key, start typing the program name, enter)

**Comment by ikeydoherty** [comment]
Fwiw this is probably the most reported (and thus closed) issue :)

The menu is bound to the panel-main-menu gsettings binding. in Evolve OS that is <Super_L>
However Mutter by default uses that for an overlay key, which we then change to F12. In Evolve OS this functionality is default, however do not have any influence over the defaults of downstream usage :/

**Comment by kallisti5** [comment]
Ah. Sucks mutter is stealing it.  Ok.   I'll see if I can get a bug in mutter openend (if there isn't one already)

**Comment by ikeydoherty** [comment]
org.gnome.mutter overlay-key, fwiw :)
