### ISSUE TITLE
Debian/Sparky Linux integration (was: Black screen)

### ISSUE THREAD

**Issue by pavroo** [evolve-os/budgie-desktop#153]
Hi
I have sucessfuly installed Budgie Desktop on Debian testing 64 bit. Works fine, no problems by now.
I also installed the desktop on 32 bit (i686) Debian testing installation. But the desktop is black (no wallpaper) and the menu is empty - there is only a visible message: Sorry, no items found.
Any chance to fix it, please?
Regards
pavroo

**Comment by Ringstaart** [comment]
Install the "gnome-menus" and "gnome-control-center" packages. Run the GNOME control center, and set a background. The default background, which uses a XML format, doesn't work properly on Budgie, but if you select a normal image file as a background it will work. You might need to restart the session to get the menu to work.

The 64 bit computer probably has GNOME installed, or had it installed in the past, so it had the missing packages right away.

**Comment by pavroo** [comment]
Installed 'gnome-menus' package solved problem with empty menu.
After setting up a custom wallpaper, I got it back.
Problems solved, thank's a lot.

I am aware that the Budgie Desktop is still under development, so I am only adding that the 32 bit Budgie freeze a few times on one session today.

Anyway I am gonna build 'budgie-desktop' debs for Debian (testing) so they will be available in Sparky repos soon. 

Thank's again

**Comment by ikeydoherty** [comment]
Cheers @Ringstaart :)

@pavroo I had to do a bit of Googling to find out what sparky was, turns out a community member mentioned the project to me :) I saw in a forum post you recommended adding the PPA to Debian... Personally I wouldn't recommend brining Ubuntu binaries into Debian, especially when Ubuntu packages are invariably patched up to the eyeballs (case in point: gtk)

As for the several freezes per day, I assure you that's not normal :) Not from git builds anyway.. What leads to these situations to cause them ?

**Comment by pavroo** [comment]
Hi Ikey, thank's for your respond.
No PPA for sure - it must be a kind of a mistake, I think.
I compiled Budgie on both 32 and 64 bit Debian's testing base.

I saw freezing on 32 bit desktop when:
1. Opened the menu - empty before and fully working after installing 'gnome-menus' as well
2. I tried to set custom wallpaper - I opened  gnome-settings, then nautilus to add the wallpaper, then I closed gnome-settings but I couldn't close nautilus
3. I tried to change settings via the panel's settings - I opened the settings window and after clicking to an option's button (I tried a few times with different options) - it freezed down

It's all what I remember now, anyway the logout option worked fine to let me login again so the freezed window has been closed itself.

**Comment by pavroo** [comment]
I have built debs and installed them on fresh Sparky/Debian testing installations.
The applications I mentioned before don't freeze any more on 32 bit system.
Looks like my production system has something installed what made a problem or doesn't have what effected as I said.
Anyway Budgie desktop from debs work fine now on my both (clear) installations.

**Comment by ikeydoherty** [comment]
Awesome! :)

**Comment by ikeydoherty** [comment]
We've had a discussion on our forums @pavroo and GeneC encountered a problem with gnome-settings-daemon on Debian.
As such, I've accommodated for the difference in XDG-ness with e8c24ef4ebe12b628120a241bd8045f1309353cd

(i.e. gnome-settings-daemon will autostart. Will need verification though :P)

**Comment by pavroo** [comment]
I have rebuilt budgie and the problem is solved (on my machine).
I will make new debs now to let our community members test it.

**Comment by ikeydoherty** [comment]
Awesome, awesome :)
Could you also confirm if mediakeys will now work for you? :D 

c3cfb2e65936dc96c4391ffff758c39202dfe9c5

**Comment by pavroo** [comment]
It was working before and works now as well.

Anyway I'd like to build (maybe tomorrow) a testing iso with Budgie on the top of Debian/Sparky to let more guys test it on 32 and 64 bit machines. I've been playing with Budgie for a week and I have to say that I really like it. Hope you will keep your work on :)

**Comment by ikeydoherty** [comment]
Sounds cool :)

Well I've been at Budgie for over a year now... :P

**Comment by pavroo** [comment]
I know that, I keep following you for a long while... 
It's my post about Evolve made 5-6 months ago http://linuxiarze.pl/evolve-os-i-budgie-desktop/
and a few about Solus http://linuxiarze.pl/?s=solus  :)

**Comment by pavroo** [comment]
There is one more small issue.
The log out option works on my hard drive installations - installed both from git and my debs.
But it doesn't work on my virtualbox installations. I said nothing about that because I didn't check it before.
But one of our community members reported the same problem found on his hard drive installation.

**Comment by ikeydoherty** [comment]
Ongoing issue atm, pending a session rewrite into a dbus service

**Comment by ikeydoherty** [comment]
Issues resolved, remainder is logout issue, which is already a separate known issue. Closing.
