### ISSUE TITLE
Applications Missing From Launcher

### ISSUE THREAD

**Issue by funnylookinhat** [evolve-os/budgie-desktop#155]
I compiled budgie-desktop from source on Ubuntu Gnome 15.04 and everything seems to be running well - but tons of applications are missing from the launcher.  Here's an obvious one ( gnome-terminal ) - I even pinned it and it still won't show up in search results.

![term](https://cloud.githubusercontent.com/assets/397918/6073423/5a581ec6-ad6b-11e4-90d4-911a94273164.png)

I'm not sure if it's related, but my gnome-control-center is nearly empty as well...

![control-center](https://cloud.githubusercontent.com/assets/397918/6073436/8a6afd2c-ad6b-11e4-861c-4fa13d63ac25.png)

**Comment by ikeydoherty** [comment]
Please install gnome-menus and gnome-control-center (That is ubuntu's fork)

**Comment by funnylookinhat** [comment]
No dice.  Those packages were already installed, so I tried running dpkg-reconfigure on them both, no change.  Then I tried removing and re-adding them, still no go.

How does Budgie get the list of applications it puts in the app launcher?  I'm wondering if there is a command I can run to re-build that list ( or maybe I could just write some code to do that? ).

**Comment by LeoIannacone** [comment]
@funnylookinhat try to add this line to `/usr/share/xsessions/budgie-desktop.desktop` file to fix Gnome Control Center:
```
DesktopNames=GNOME
```
You have to logout then to apply changes.

Reason:
In Ubuntu many application have been patched to act differently depending on which DE is running.

More specifically, the DesktopNames makes GDM to properly set $XDG_CURRENT_DESKTOP enviroment variable, which is used to check the DE in Ubuntu patched application.. 
See nautilus for example, in this patch if XDG_CURRENT_DESKTOP is not GNOME the GtkHeaderbar is not used:
http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/vivid/nautilus/vivid/view/head:/debian/patches/ubuntu_show_titlebar.patch#L68

**Comment by funnylookinhat** [comment]
@LeoIannacone That worked!  Thank you so much!

**Comment by funnylookinhat** [comment]
@LeoIannacone Before I open another bug - maybe you know the answer... the power menu ( "Shutdown", etc. ) doesn't seem to work or do anything.  I have a feeling it's a similar configuration issue that's specific to Ubuntu.  Any ideas?
