### ISSUE TITLE
Arrow key navigation in launcher

### ISSUE THREAD

**Issue by theSoenke** [evolve-os/budgie-desktop#162]
It would be good if i could navigate with arrow keys in the launcher. When i search for something i often don't want to select the first result and it should be possible to select the right one with the arrow keys and hit enter

**Comment by ikeydoherty** [comment]
Yup, good call. Gimme a few minutes..

**Comment by ikeydoherty** [comment]
Or one ;)

**Comment by theSoenke** [comment]
that was fast :) awesome

**Comment by ikeydoherty** [comment]
Hah no probs :) Tbh we do need to do something about the theming side though, right now the dashed box for focus is a bit.. well. Meh. :/
