### ISSUE TITLE
Problem with Qt?

### ISSUE THREAD

**Issue by theSoenke** [evolve-os/budgie-desktop#165]
Qt4 applications are looking ugly with budgie. Any way to fix this?

![qtassistant](https://cloud.githubusercontent.com/assets/1757301/6177156/8142d53c-b304-11e4-8891-1d967d44aa39.png)

**Comment by ikeydoherty** [comment]
Can probably use the qtconfig tool to set the theme correctly I think? (i.e. use GTK theme)

**Comment by theSoenke** [comment]
The qtconfig tool seems not to exist on arch. And when i switch back to gnome qt looks fine

**Comment by rilian-la-te** [comment]
use qtconfig-qt4 on arch:)

**Comment by theSoenke** [comment]
Thanks. qtconfig-qt4 worked
