### ISSUE TITLE
support systemd user sessions

### ISSUE THREAD

**Issue by zabbal** [evolve-os/budgie-desktop#28]
Would be great to see support for "systemd --user" type of user sessions: collection of units automatically started for particular user upon login.

See https://github.com/sofar/user-session-units and http://man7.org/linux/man-pages/man8/systemd-user-sessions.8.html for example.
Also https://wiki.archlinux.org/index.php/Systemd/User might be handy example.

**Comment by ikeydoherty** [comment]
Currently not within our scope, given active efforts to port Budgie to BSD. Will accept patches..
