### ISSUE TITLE
Suggestion: Backdrop for launcher

### ISSUE THREAD

**Issue by Justinzobel** [evolve-os/budgie-desktop#48]
On lighter backgrounds the 9 dot icon that makes up the launcher can almost disappear (would if the background was 100% white).

Maybe something along the lines of elementary's adjusting opacity from wingpanel might help with situations like this.

Link https://code.launchpad.net/~elementary-pantheon/wingpanel/background-opacity

**Comment by ikeydoherty** [comment]
Given our choice to enable custom colours in the future, I will close this.
