### ISSUE TITLE
Extra Settings

### ISSUE THREAD

**Issue by Quacky2200** [evolve-os/budgie-desktop#55]
Some settings that could be useful:
Animations: On | Off
Default - On
Some devices are incapable of displaying the latest animations if they are more than 4-5 years old. Disabling them will reduce graphic card usage and will hopefully increase speed.

CSS-Theming: On | Off
Default - On
Is that theme you like turning your desktop panel into a mess? Turn CSS theming off to use the default basic theme

Edge-Tiling-Highlight: On | Off
Default - On
It can sometimes be tricky detecting whether the application you're dragging will dock to the edge your mouse is currently bumping into, turning this on gives you this indication.

System-Tray: All | Basic | None
Default - All
The system tray is important when dealing with your favourite hidden applications and allow most applications to run whilst taking the least amount of space on panel's window list. The "All" setting will show all your applications and basic system icons. Although if you're simplistic, the "Basic" setting will hide the unnecessary icons but not the basic icons such as the clock, sound and network settings

Battery-Meter: Always Show | Laptop Only | None
Default - Laptop Only
The battery meter is the most valuable system icon for your portable devices so you know when to plug them in. "Always Show" will show the icon even if you're running budgie-panel on a desktop.

Date-Format: DD/MM/YY | YY/MM/DD | MM/DD/YY
Default - Localised to their location
-       -

Date-Day-String: Full | Short | None
Default - None
Showing the day is useful when you want to know the current day quickly. However, it is turned off to improve simplicity and space on the panel.

Date-Month-String: Full | Short | None
Default - None
Showing the month is useful when you want to know the current month quickly. However, it is turned off to improve simplicity and space on the panel.

Date-Year-String: Full | Short | None
Default - None
Showing the year is useful when you want to know the year quickly. However, it is turned off to improve simplicity and space on the panel.

Time-Format: 24-Hour | 12-Hour
Default - "24-Hour"
The 24-Hour format is quicker to read and saves space on the panel. Whereas the 12-Hour format provides AM and PM only using 12 hours like an analog clock.

Time-Show-Seconds: On | Off
Default - Off
Some people love to watch the seconds go by (especially at work) but to me, as a computer, seconds are too slow. So I turned them off.

User-Fast-Switching: Full Name | Username | None
Default - None
Do you have multiple users and want to quickly switch users? Using "Full Name" will look formal and better than using the "Username" setting but some people might prefer to be reminded of their username.

User-Fast-Switching-Icon: Show | Hide
Default - Hide
Some selfie loving people like to view themselves all day which is why they love taking selfies! Showing this icon will remind them off their proud account picture. This will only show with the User fast switching being turned on.

Power-Button: Show | Hide
Default - Hide
Muscle memory still might remember that power button in the right hand corner of a panel when using XFCE and Gnome, which is why it's handy to have this option.

Disclaimer: It might not be the best settings on earth but at least people will have the options to configure the panel nicely. The descriptions were just something I made quickly so you can change that if you need to... :)

**Comment by ikeydoherty** [comment]
Settings UI was overhauled a while back. As and when we need new options they'll go there..
