### ISSUE TITLE
Budgie-Desktop Won't Start from GDM

### ISSUE THREAD

**Issue by Saroufim** [evolve-os/budgie-desktop#62]
GDM would log the user immediately out if attempting to log in to Budgie-desktop. This happens on openSUSE 13.1 with GDM 3.12.2 and Budgie-desktop 7.

**Comment by ikeydoherty** [comment]
Closing for now due to inability to now test (ironically) with 3.12, but only 3.14..

**Comment by necrose99** [comment]
https://www.spike-pentesting.org/ or App-wichcraft (github) can be used to test till the cows come home, 
on Gentoo or Sabayon based systems,  however Muddler our distro master has had a number of issues building however , if needed I'll be happy to spin up a test build , and see how she goes. 
necrose99 on Freenode or #spike-pentesting/#spike-pentesting-dev (note the build server sometimes spams the dev chan... as it builds packages... 
anyhow happy to oblige in testing on Gentoo/Sabayon based systems...
