### ISSUE TITLE
Skype incoming call notifications don't show ~50% of the time

### ISSUE THREAD

**Issue by iv597** [evolve-os/budgie-desktop#78]
This seems to be quite hit and miss and might be something we have to tell mutter to do some weird corner case for. Only discovered this as I use Skype to communicate with my work clients and, well, hearing them call you but not finding an answer icon is interesting to say the least.

Maybe someone can do some testing on this to see what the deal is. Running latest budgie-desktop from Git, Skype 4.3.0.37 on Arch Linux x86_64

**Comment by ikeydoherty** [comment]
Is this still valid with new versions? Specifically 3.14.

**Comment by iv597** [comment]
I've been on a Macbook Pro since mid-November or so and haven't gotten around to setting up a dual-boot (still), so I haven't tested this lately :(

**Comment by ikeydoherty** [comment]
np! When we get our 32-bit sorted out I'll do a battery-teting with skype :)

**Comment by ikeydoherty** [comment]
Closing as I'll end up testing this myself.
