### ISSUE TITLE
Alt-tab cyles only beetween two tasks

### ISSUE THREAD

**Issue by dspangenberg** [evolve-os/budgie-desktop#85]
If I try to switch beetween tasks alt-tab cyles only beetween two "random" tasks. 

Example:
Open: Terminal - Firefox - Chrome- Gitg - Sublime Text

Terminal <-> Firefox
Chrome <-> Firefox
Gitg <-> Firefox
Sublime text <-> GItg

**Comment by ikeydoherty** [comment]
Resolved a while ago.
