### ISSUE TITLE
Tray icon applet strange behavior

### ISSUE THREAD

**Issue by squarerootfury** [evolve-os/budgie-desktop#88]
The tray icon applet has a strange behavior:

When I assume I have one icon in the tray, the icon is displayed, and left and right is a lot more free space. When I remove the applet and re-add it, it gets more wide. I can repeat this until it gets wider than the screen.

Unfortunately, I cannot add any screenshots, beause of #87 :/

**Comment by ikeydoherty** [comment]
A detailed explanation as to why we won't fix this is available via #120 
In short there's nowt I can do about it without overhauling Budgie for the sake of a legacy system we are intent on providing an alternative to.
